server:
  port: 8082
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id : conversion-service
          uri : lb://CONVERSION-SERVICE
          predicates :
            - Path=/conversion/**
          filters:
            - name: CircuitBreaker
              args:
                name: conversion-service
                fallbackuri: forward:/conversionServiceFallback
        - id: exchange-rate-service
          uri: lb://EXCHANGE-RATE-SERVICE
          predicates:
            - Path=/exchangeRate/**
          filters:
            - name: CircuitBreaker
              args:
                name: exchange-rate-service
                fallbackuri: forward:/exchangeRateServiceFallback